### ISSUE TITLE
[Discussion] Generating distinct n-tuple combinations as a optimized input space search strategy 

### ISSUE THREAD

**Issue by AlgorithmsAreCool** [AnthonyLloyd/CsCheck#7]
Couldn't sleep and stumbled on [this](https://github.com/microsoft/pict) which eventually lead me to [this paper out of the NIST]( https://csrc.nist.rip/CSRC/media/Presentations/Introducing-Combinatorial-Testing-in-Large-Organiz/images-media/kuhn-astqb-14.pdf)

I haven't fully studied how your code traverses the input space, but it seems to be breadth-first-ish across dimensions (Gens), which makes sense to ensure each dimension gets some coverage quickly. But the idea in the paper is to compute a minimal set of test cases that guarantees coverage of all n-ary combinations of input dimensions values. The observation being that most bugs are an interaction between small numbers of problematic parameters (2 - 6 with high probability in their study). Even if the input space might be near-infinite, covering 2-way or 3-way interactions might be a tractable problem. 

I have primarily been using CsCheck to validate system business models and config settings (as opposed to numerical problems). Typically, this involves me sampling several Gens to construct a single model entity. Overall, the input space can be very highly dimensional, and test coverage begins to become a concern. To combat this I typically have "lower level" tests that focus on a smaller chunks of the model because the complexity of the overall model might be too big to get confidence that we are searching all the corners in a reasonable amount of time. (This is a gut reaction and not backed up by numbers).

Having an option to change the way the input space is searched to cover all these "corners" seems valuable when the models get big. It might also allow a smaller set of higher level tests to cover dangerous states better than normal random tests. I need to think about how to represent the models in an ergonomic way so tests are easy to write and then how to have an engine enumerate the input dimensions and compute a covering set for the specified n-arity and interaction depth. There is also a lot of [prior art](https://www.pairwise.org/tools.html) here that I want to study also.

Are you familiar with this testing methodology? What are your thoughts about the idea?

**Comment by AnthonyLloyd** [comment]
I'm not exactly familiar but it makes complete sense and echos other things I know. I'm going to need to think about this more and how it can be incorporated.

For random number generators there are n-dimensional sobol sequences and also quasi-monte carlo methods. These basically go through the n-dim space in the most spread out way.

What you've described would be a bit different in that for example a 3-d space you'd want to pick a point in the centre first and then (1,0,0), (-1,0,0),(0,1,0)...(0,0,-1) then (1,1,0)...(0,-1,-1) or maybe just skp to the 2-dim interactions because they cover the 1-d cases.

We also have more of a tree rather than an n-dim space which may or may not be a problem (monads are powerful).

I'll think some more. It's definitely interesting because I can see it could be much more efficient for finding real world cases.

**Comment by AlgorithmsAreCool** [comment]
Update : This issue I think has some juice for the squeeze, however it has at least one distinct challenge. The algorithm to compute an efficient set of search points is computationally expensive. I need to experimentally validate just how expensive it is.

**Comment by AnthonyLloyd** [comment]
Will close this now. Happy to revist if an algorithm presents itself.
